# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chacha_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chacha_IOS
  pod 'SnapKit', '~> 3.0.0'
  pod 'pop', '~> 1.0'
end

target 'chacha_Mac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chacha_Mac
  pod 'SnapKit', '~> 3.0.0'
  pod 'pop', '~> 1.0'
end
